export const API_ENDPOINTS = {
  auth: {
    signup: '/auth/signup',
    login: '/auth/login',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    me: '/me',
  },
  submissions: {
    list: '/submissions/',
    detail: (id: string) => `/submissions/${id}`,
    create: '/submissions/',
    update: (id: string) => `/submissions/${id}/`,
    uploadFile: (id: string) => `/submissions/${id}/upload-file/`,
    submit: (id: string) => `/submissions/${id}/submit/`,
    resubmit: (id: string) => `/submissions/${id}/resubmit/`,
    delete: (id: string) => `/submissions/${id}`,
  },
  editor: {
    submissions: '/editor/submissions',
    submissionDetail: (id: string) => `/editor/submissions/${id}`,
    reviewers: '/editor/reviewers',
    startScreening: (id: string) => `/editor/submissions/${id}/start-screening/`,
    deskReject: (id: string) => `/editor/submissions/${id}/desk-reject/`,
    sendToReview: (id: string) => `/editor/submissions/${id}/send-to-review/`,
    inviteReviewer: (id: string) => `/editor/submissions/${id}/invite-reviewer/`,
    moveToDecision: (id: string) => `/editor/submissions/${id}/move-to-decision/`,
    makeDecision: (id: string) => `/editor/submissions/${id}/decision/`,
    publish: (id: string) => `/editor/submissions/${id}/publish/`,
    remindReviewer: (assignmentId: string) => `/editor/review-assignments/${assignmentId}/remind/`,
  },
  reviewer: {
    assignments: '/reviewer/assignments/',
    assignmentDetail: (id: string) => `/reviewer/assignments/${id}`,
    accept: (id: string) => `/reviewer/assignments/${id}/accept/`,
    decline: (id: string) => `/reviewer/assignments/${id}/decline/`,
    submitReview: (id: string) => `/reviewer/assignments/${id}/submit-review/`,
    acceptByToken: '/reviewer/accept-by-token/',
    declineByToken: '/reviewer/decline-by-token/',
  },
  public: {
    articles: '/articles/',
    articleDetail: (slug: string) => `/articles/${slug}/`,
    topicAreas: '/topic-areas',
    editorialBoard: '/editorial-board',
  },
  admin: {
    approveReviewer: (userId: number) => `/admin/users/${userId}/approve-reviewer/`,
    approveEditor: (userId: number) => `/admin/users/${userId}/approve-editor/`,
    rejectReviewer: (userId: number) => `/admin/users/${userId}/reject-reviewer/`,
    rejectEditor: (userId: number) => `/admin/users/${userId}/reject-editor/`,
  },
} as const;
